// Code generated by goctl. DO NOT EDIT!
// Source: account.proto

package server

import (
	"context"

	"rpc/account"
	"rpc/internal/logic"
	"rpc/internal/svc"
)

type AccountServer struct {
	svcCtx *svc.ServiceContext
	account.UnimplementedAccountServer
}

func NewAccountServer(svcCtx *svc.ServiceContext) *AccountServer {
	return &AccountServer{
		svcCtx: svcCtx,
	}
}

func (s *AccountServer) ExamToken(ctx context.Context, in *account.TokenExamineRequest) (*account.TokenExamineResponse, error) {
	l := logic.NewExamTokenLogic(ctx, s.svcCtx)
	return l.ExamToken(in)
}
