// Code generated by goctl. DO NOT EDIT!
// Source: account.proto

package account

import (
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Account interface {
		ExamToken(ctx context.Context, in *TokenExamineRequest, opts ...grpc.CallOption) (*TokenExamineResponse, error)
	}

	defaultAccount struct {
		cli zrpc.Client
	}
)

func NewAccount(cli zrpc.Client) Account {
	return &defaultAccount{
		cli: cli,
	}
}

func (m *defaultAccount) ExamToken(ctx context.Context, in *TokenExamineRequest, opts ...grpc.CallOption) (*TokenExamineResponse, error) {
	client := NewAccountClient(m.cli.Conn())
	return client.ExamToken(ctx, in, opts...)
}
